# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170224_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(default=datetime.datetime.now, verbose_name='hour')),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BillSegment', verbose_name='amendment')),
            ],
            options={
                'verbose_name': 'history notification',
                'verbose_name_plural': 'history notifications',
                'ordering': ('-hour',),
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('periodicity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20, verbose_name='periodicity')),
                ('status', models.BooleanField(default=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bill', verbose_name='bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together=set([('user', 'bill')]),
        ),
    ]
