#!/bin/bash
python wikilegis/manage.py makemigrations
python wikilegis/manage.py migrate
coverage run wikilegis/manage.py test_apps
coverage report
echo $'\nRunning flake8...\n'
flake8 wikilegis
npm run lint
