# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 14:03
from __future__ import unicode_literals

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditiveAmendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('upvote_count', models.IntegerField(default=0, verbose_name='upvotes count')),
                ('downvote_count', models.IntegerField(default=0, verbose_name='downvotes count')),
                ('comments_count', models.IntegerField(default=0, verbose_name='comments count')),
                ('participation_count', models.IntegerField(default=0, verbose_name='participations count')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('number', models.CharField(blank=True, max_length=200, null=True, verbose_name='number')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.AdditiveAmendment', verbose_name='segment parent')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('upvote_count', models.IntegerField(default=0, verbose_name='upvotes count')),
                ('downvote_count', models.IntegerField(default=0, verbose_name='downvotes count')),
                ('comments_count', models.IntegerField(default=0, verbose_name='comments count')),
                ('participation_count', models.IntegerField(default=0, verbose_name='participations count')),
                ('title', models.CharField(max_length=255, verbose_name='subject')),
                ('epigraph', models.CharField(max_length=255, null=True, verbose_name='epigraph')),
                ('description', models.TextField(verbose_name='description')),
                ('closing_date', models.DateField(verbose_name='closing date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='1', max_length=20, verbose_name='status')),
                ('is_visible', models.BooleanField(default=False, verbose_name='visible')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_bills', to=settings.AUTH_USER_MODEL, verbose_name='allowed users')),
                ('reporting_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='reporting member')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='BillReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('reference_file', models.FileField(upload_to=core.utils.references_filename, verbose_name='reference_file')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bill', verbose_name='bill')),
            ],
            options={
                'verbose_name': 'Bill Reference',
                'verbose_name_plural': 'Bill References',
            },
        ),
        migrations.CreateModel(
            name='BillSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('upvote_count', models.IntegerField(default=0, verbose_name='upvotes count')),
                ('downvote_count', models.IntegerField(default=0, verbose_name='downvotes count')),
                ('comments_count', models.IntegerField(default=0, verbose_name='comments count')),
                ('participation_count', models.IntegerField(default=0, verbose_name='participations count')),
                ('amendments_count', models.IntegerField(default=0, verbose_name='amendments count')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('number', models.CharField(blank=True, max_length=200, null=True, verbose_name='number')),
                ('content', models.TextField(verbose_name='content')),
                ('additive_amendments_count', models.IntegerField(default=0)),
                ('modifier_amendments_count', models.IntegerField(default=0)),
                ('supress_amendments_count', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.Bill', verbose_name='bill')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.BillSegment', verbose_name='segment parent')),
            ],
            options={
                'verbose_name': 'segment',
                'verbose_name_plural': 'segments',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='BillTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('icon', models.ImageField(upload_to=core.utils.theme_icon_filename, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Bill Theme',
                'verbose_name_plural': 'Bill Themes',
            },
        ),
        migrations.CreateModel(
            name='BillVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.Bill', verbose_name='bill')),
            ],
            options={
                'verbose_name': 'Bill Video',
                'verbose_name_plural': 'Bill Videos',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=500, verbose_name='text')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='ModifierAmendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('upvote_count', models.IntegerField(default=0, verbose_name='upvotes count')),
                ('downvote_count', models.IntegerField(default=0, verbose_name='downvotes count')),
                ('comments_count', models.IntegerField(default=0, verbose_name='comments count')),
                ('participation_count', models.IntegerField(default=0, verbose_name='participations count')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('number', models.CharField(blank=True, max_length=200, null=True, verbose_name='number')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.ModifierAmendment', verbose_name='segment parent')),
                ('replaced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_amendments', to='core.BillSegment', verbose_name='replaced')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('presentation_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='presentation name')),
                ('editable', models.BooleanField(default='True', verbose_name='editable')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.SegmentType', verbose_name='parent type')),
            ],
            options={
                'verbose_name': 'Segment Type',
                'verbose_name_plural': 'Segment Types',
            },
        ),
        migrations.CreateModel(
            name='SupressAmendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('upvote_count', models.IntegerField(default=0, verbose_name='upvotes count')),
                ('downvote_count', models.IntegerField(default=0, verbose_name='downvotes count')),
                ('comments_count', models.IntegerField(default=0, verbose_name='comments count')),
                ('participation_count', models.IntegerField(default=0, verbose_name='participations count')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('number', models.CharField(blank=True, max_length=200, null=True, verbose_name='number')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.SupressAmendment', verbose_name='segment parent')),
                ('segment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SegmentType', verbose_name='segment type')),
                ('supressed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supress_amendments', to='core.BillSegment', verbose_name='supressed')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpDownVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('vote', models.BooleanField(choices=[(True, 'Up Vote'), (False, 'Down Vote')], default=False, verbose_name='vote')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='modifieramendment',
            name='segment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SegmentType', verbose_name='segment type'),
        ),
        migrations.AddField(
            model_name='billsegment',
            name='segment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SegmentType', verbose_name='segment type'),
        ),
        migrations.AddField(
            model_name='bill',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BillTheme', verbose_name='theme'),
        ),
        migrations.AddField(
            model_name='additiveamendment',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additive_amendments', to='core.BillSegment', verbose_name='reference'),
        ),
        migrations.AddField(
            model_name='additiveamendment',
            name='segment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SegmentType', verbose_name='segment type'),
        ),
        migrations.AlterUniqueTogether(
            name='updownvote',
            unique_together=set([('user', 'object_id', 'content_type')]),
        ),
    ]
