# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:12
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additiveamendment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='modifieramendment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='supressamendment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='supressamendment',
            name='parent',
        ),
        migrations.AddField(
            model_name='billreference',
            name='url',
            field=models.URLField(null=True, verbose_name='reference url'),
        ),
        migrations.AlterField(
            model_name='billreference',
            name='reference_file',
            field=models.FileField(null=True, upload_to=core.utils.references_filename, verbose_name='reference file'),
        ),
        migrations.AlterField(
            model_name='billtheme',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='billtheme',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.theme_icon_filename, verbose_name='icon'),
        ),
    ]
