# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:16
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additiveamendment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='modifieramendment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='supressamendment',
            name='parent',
        ),
        migrations.AddField(
            model_name='billreference',
            name='url',
            field=models.URLField(null=True, verbose_name='reference url'),
        ),
        migrations.AlterField(
            model_name='billreference',
            name='reference_file',
            field=models.FileField(null=True, upload_to=core.utils.references_filename, verbose_name='reference file'),
        ),
    ]
