# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:53
from __future__ import unicode_literals

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Projeto de lei', 'verbose_name_plural': 'Projetos de lei'},
        ),
        migrations.AlterModelOptions(
            name='billsegment',
            options={'ordering': ('order',), 'verbose_name': 'trecho', 'verbose_name_plural': 'trechos'},
        ),
        migrations.AlterModelOptions(
            name='billtheme',
            options={'verbose_name': 'Tema de projeto de lei', 'verbose_name_plural': 'Temas de projeto de lei'},
        ),
        migrations.AlterModelOptions(
            name='segmenttype',
            options={'verbose_name': 'Tipo de Trecho', 'verbose_name_plural': 'Tipos de Trecho'},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='reporting_member',
        ),
        migrations.AlterField(
            model_name='additiveamendment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='additiveamendment',
            name='content',
            field=models.TextField(verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='additiveamendment',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='additiveamendment',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additive_amendments', to='core.BillSegment', verbose_name='referência'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_bills', to=settings.AUTH_USER_MODEL, verbose_name='usuários permitidos'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='closing_date',
            field=models.DateField(verbose_name='data de encerramento'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='epigraph',
            field=models.CharField(max_length=255, null=True, verbose_name='epígrafe'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='visível'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('closed', 'Fechado')], default='1', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BillTheme', verbose_name='tema'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(max_length=255, verbose_name='assunto'),
        ),
        migrations.AlterField(
            model_name='billreference',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.Bill', verbose_name='projeto de lei'),
        ),
        migrations.AlterField(
            model_name='billreference',
            name='reference_file',
            field=models.FileField(null=True, upload_to=core.utils.references_filename, verbose_name='arquivo de referência'),
        ),
        migrations.AlterField(
            model_name='billreference',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='billreference',
            name='url',
            field=models.URLField(null=True, verbose_name='url de referência'),
        ),
        migrations.AlterField(
            model_name='billsegment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.Bill', verbose_name='projeto de lei'),
        ),
        migrations.AlterField(
            model_name='billsegment',
            name='content',
            field=models.TextField(verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='billsegment',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='billsegment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.BillSegment', verbose_name='trecho ancestral'),
        ),
        migrations.AlterField(
            model_name='billtheme',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='billtheme',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.theme_icon_filename, verbose_name='ícone'),
        ),
        migrations.AlterField(
            model_name='billvideo',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.Bill', verbose_name='projeto de lei'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='modifieramendment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='modifieramendment',
            name='content',
            field=models.TextField(verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='modifieramendment',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='modifieramendment',
            name='replaced',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_amendments', to='core.BillSegment', verbose_name='substituído'),
        ),
        migrations.AlterField(
            model_name='segmenttype',
            name='editable',
            field=models.BooleanField(default='True', verbose_name='editável'),
        ),
        migrations.AlterField(
            model_name='segmenttype',
            name='parents',
            field=models.ManyToManyField(related_name='children', to='core.SegmentType', verbose_name='tipo ancestral'),
        ),
        migrations.AlterField(
            model_name='segmenttype',
            name='presentation_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nome de apresentação'),
        ),
        migrations.AlterField(
            model_name='supressamendment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='supressamendment',
            name='content',
            field=models.TextField(verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='supressamendment',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='supressamendment',
            name='supressed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supress_amendments', to='core.BillSegment', verbose_name='suprimido'),
        ),
        migrations.AlterField(
            model_name='updownvote',
            name='vote',
            field=models.BooleanField(choices=[(True, 'Voto a favor'), (False, 'Voto contra')], default=False, verbose_name='voto'),
        ),
    ]
