# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170127_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supressamendment',
            name='content',
        ),
    ]
