# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170301_1718'),
        ('core', '0002_auto_20170224_1023'),
    ]

    operations = [
    ]
