# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170224_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additiveamendment',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='billsegment',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='modifieramendment',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='supressamendment',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
    ]
