# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170321_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenttype',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='core.SegmentType', verbose_name='tipo ancestral'),
        ),
    ]
