# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_supressamendment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='participation_count',
        ),
        migrations.AddField(
            model_name='bill',
            name='amendments_count',
            field=models.IntegerField(default=0, verbose_name='amendments count'),
        ),
    ]
