# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20170321_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do autor')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Região')),
                ('party', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partido')),
                ('register_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id de registro')),
            ],
            options={
                'verbose_name': 'Bill Author',
                'verbose_name_plural': 'Bill Authors',
            },
        ),
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_number', models.IntegerField(verbose_name='Número da Proposição')),
                ('proposal_year', models.IntegerField(verbose_name='Ano da Proposição')),
                ('situation', models.CharField(blank=True, max_length=400, null=True, verbose_name='Situação')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.BillAuthor', verbose_name='Autor')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='core.Bill', verbose_name='Projeto de lei')),
            ],
            options={
                'verbose_name': 'Bill Info',
                'verbose_name_plural': 'Bill Infos',
            },
        ),
        migrations.CreateModel(
            name='ProposalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Proposal Type',
                'verbose_name_plural': 'Proposal Types',
            },
        ),
        migrations.CreateModel(
            name='ReportingMember',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id do Relator')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Parlamentar')),
                ('party', models.CharField(max_length=255, verbose_name='Partido')),
                ('region', models.CharField(max_length=2, verbose_name='Região')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'ReportingMember',
                'verbose_name_plural': 'ReportingMembers',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='billinfo',
            name='proposal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.ProposalType', verbose_name='Tipo da Proposição'),
        ),
        migrations.AddField(
            model_name='billinfo',
            name='reporting_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.ReportingMember', verbose_name='Relator'),
        ),
    ]
