# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_bill_reporting_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Author Name')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('party', models.CharField(blank=True, max_length=255, null=True, verbose_name='Party')),
                ('register_id', models.IntegerField(blank=True, null=True, verbose_name='Register ID')),
            ],
            options={
                'verbose_name': 'Bill Author',
                'verbose_name_plural': 'Bill Authors',
            },
        ),
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_number', models.IntegerField(verbose_name='Proposal Number')),
                ('proposal_year', models.IntegerField(verbose_name='Proposal Year')),
                ('situation', models.CharField(blank=True, max_length=400, null=True, verbose_name='Situation')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.BillAuthor', verbose_name='Author')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='core.Bill', verbose_name='Bill')),
            ],
            options={
                'verbose_name': 'Bill Info',
                'verbose_name_plural': 'Bill Infos',
            },
        ),
        migrations.CreateModel(
            name='ProposalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Proposal Type',
                'verbose_name_plural': 'Proposal Types',
            },
        ),
        migrations.CreateModel(
            name='ReportingMember',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Reporting Member ID')),
                ('name', models.CharField(max_length=255, verbose_name='Parliamentary Name')),
                ('party', models.CharField(max_length=255, verbose_name='Party')),
                ('region', models.CharField(max_length=2, verbose_name='Region')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'ReportingMember',
                'verbose_name_plural': 'ReportingMembers',
            },
        ),
        migrations.AddField(
            model_name='billinfo',
            name='proposal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.ProposalType', verbose_name='Proposal Type'),
        ),
        migrations.AddField(
            model_name='billinfo',
            name='reporting_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.ReportingMember', verbose_name='Reporting Member'),
        ),
    ]
