# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camara_deputados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billauthor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='billauthor',
            name='party',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='billauthor',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='billauthor',
            name='register_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Register ID'),
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.BillAuthor', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='core.Bill', verbose_name='Bill'),
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='proposal_number',
            field=models.IntegerField(verbose_name='Proposal Number'),
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='proposal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.ProposalType', verbose_name='Proposal Type'),
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='proposal_year',
            field=models.IntegerField(verbose_name='Proposal Year'),
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='reporting_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.ReportingMember', verbose_name='Reporting Member'),
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='situation',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='reportingmember',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Reporting Member ID'),
        ),
        migrations.AlterField(
            model_name='reportingmember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Parliamentary Name'),
        ),
        migrations.AlterField(
            model_name='reportingmember',
            name='party',
            field=models.CharField(max_length=255, verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='reportingmember',
            name='region',
            field=models.CharField(max_length=2, verbose_name='Region'),
        ),
    ]
