# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camara_deputados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Proposal Type',
                'verbose_name_plural': 'Proposal Types',
            },
        ),
        migrations.AlterField(
            model_name='billinfo',
            name='proposal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.ProposalType', verbose_name='Proposal Type'),
        ),
    ]
