# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camara_deputados', '0002_auto_20170310_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinfo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.BillAuthor', verbose_name='Author'),
        ),
    ]
